(define (problem BLOCKS-5-0)
(:domain BLOCKS)
(:objects D B A C E - block)
(:INIT (CLEAR E) (ONTABLE A) (ON E D) (ON D C) (ON C B) (ON B A) (HANDEMPTY))
(:goal (AND (ONCONVEYOR D) (ONCONVEYOR B) (ON E C) (ON C A) ))
)
